# Generated by Django 4.1.7 on 2023-05-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fishinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('labels', models.CharField(blank=True, max_length=4, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('image_url', models.TextField()),
            ],
        ),
    ]
